Repository dnd-side-project/dnd-10th-9-iOS, pull requests merged in 2024-02, with the labels that each got.

#7 Chore/#6 network foldering
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DOTCHI/DOTCHI.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DOTCHI/DOTCHI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DOTCHI/DOTCHI/DOTCHIApp.swift
  DOTCHI/DOTCHI/Global/Bases/BaseViewController.swift
  DOTCHI/DOTCHI/Global/Enums/LuckyType.swift
  DOTCHI/DOTCHI/Global/Extensions/UIViewcontroller+.swift
  DOTCHI/DOTCHI/Global/Protocols/a.swift
  DOTCHI/DOTCHI/Global/Singletons/ImageCacheManager.swift
  DOTCHI/DOTCHI/Global/Singletons/UserInfo.swift
  DOTCHI/DOTCHI/Networks/DTO/Auth/Request/SocialLoginRequestDTO.swift
  DOTCHI/DOTCHI/Networks/DTO/Auth/Response/SocialLoginResponseDTO.swift
  DOTCHI/DOTCHI/Networks/Essentials/APIConstants.swift
  DOTCHI/DOTCHI/Networks/Essentials/BaseResponseType.swift
  DOTCHI/DOTCHI/Networks/Essentials/DotchiMoyaProvider.swift
  DOTCHI/DOTCHI/Networks/Essentials/NetworkResult.swift
  DOTCHI/DOTCHI/Networks/NetworkLoggerPlugin.swift
  DOTCHI/DOTCHI/Networks/Routers/AuthRouter.swift
  DOTCHI/DOTCHI/Networks/Services/AuthService.swift
  DOTCHI/DOTCHI/Networks/Services/BaseService.swift
  DOTCHI/DOTCHI/Preview Content/Preview Assets.xcassets/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/Color.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/Contents.json
  DOTCHI/DOTCHI/Screens/Components/aaa.swift
  DOTCHI/DOTCHI/Screens/ContentView.swift
  DOTCHI/DOTCHI/Screens/Home/HomeView.swift
  DOTCHI/DOTCHI/Screens/My/aa.swift
  DOTCHI/DOTCHI/Supports/Environment.swift
  dnd-10th-9.xcodeproj/project.pbxproj
Labels: chore 🧹, add ✚, move ➡️

#15 [FEAT] 공유, 좋아요 버튼 컴포넌트 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icnComment.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icnComment.imageset/icn_comment.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icnShare.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icnShare.imageset/icn_share.svg
  DOTCHI/DOTCHI/Screens/Components/Buttons/DotchiCircleButton.swift
Labels: feat 💚, add ✚

#17 [CHORE] 컬러, 폰트 설정
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Extensions/UIFont+.swift
  DOTCHI/DOTCHI/Info.plist
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/BackgroundBlack.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiBlue.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiGray1.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiGray2.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiPink.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiRed.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Fonts/Pretendard-Black.ttf
  DOTCHI/DOTCHI/Resources/Fonts/Pretendard-ExtraBold.ttf
  DOTCHI/DOTCHI/Resources/Fonts/Pretendard-Medium.ttf
  DOTCHI/DOTCHI/Resources/Fonts/Pretendard-SemiBold.ttf
Labels: chore 🧹

#21 [CHORE] 폰트 설정
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Extensions/FontManager.swift
  DOTCHI/DOTCHI/Info.plist
  DOTCHI/DOTCHI/Resources/Fonts/Pretendard-Black.ttf
  DOTCHI/DOTCHI/Resources/Fonts/Pretendard-Bold.ttf
Labels: chore 🧹

#24 [CHORE] Tab Bar 디자인 수정
  DOTCHI/DOTCHI/Global/Extensions/FontManager.swift
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnHome.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnHome.imageset/icn_home.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnHome_fill.imageset/home_fill@1x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnHome_fill.imageset/home_fill@2x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnHome_fill.imageset/home_fill@3x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnMy.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnMy.imageset/icn_my.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPerson_fill.imageset/person_fill@1x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPerson_fill.imageset/person_fill@2x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPerson_fill.imageset/person_fill@3x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPlus.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPlus.imageset/icn_plus.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPlus.imageset/plus@1x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPlus.imageset/plus@2x.png
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnPlus.imageset/plus@3x.png
  DOTCHI/DOTCHI/Screens/ContentView.swift
  DOTCHI/DOTCHI/Screens/Home/HomeView.swift
  DOTCHI/DOTCHI/Screens/My/MyView.swift
Labels: chore 🧹

#26 [CHORE] 컬러셋, 폰트 스타일 추가
  DOTCHI/DOTCHI/Global/Bases/BaseViewController.swift
  DOTCHI/DOTCHI/Global/Extensions/UIFont+.swift
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/BackgroundBlack.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiBlue.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiGray1.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiGray2.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiPink.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/DotchiRed.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiBlack.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiBlue.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiDeepBlue.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiDeepGreen.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiDeepOrange.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiDeepPink.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiGreen.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiHgray.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiLBlue.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiLGreen.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiLOrange.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiLPink.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiLgray.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiMgray.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiOrange.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiPink.colorset/Contents.json
  DOTCHI/DOTCHI/Screens/Home/HomeView.swift
  DOTCHI/DOTCHI/Screens/My/MyView.swift
Labels: chore 🧹

#27 [FEAT] 행운별 모아보기 UI 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Networks/Essentials/APIConstants.swift
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLuckyF.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLuckyF.imageset/imgLuckyF.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgTest.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgTest.imageset/imgTest.svg
  DOTCHI/DOTCHI/Screens/ContentView.swift
  DOTCHI/DOTCHI/Screens/Home/CollectionView.swift
  DOTCHI/DOTCHI/Supports/Environment.swift
Labels: chore 🧹, feat 💚

#28 [FEAT] 둘러보기 뷰 UI 구현, CardFrontUIView 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Entities/CardFrontEntity.swift
  DOTCHI/DOTCHI/Entities/CardUserEntity.swift
  DOTCHI/DOTCHI/Global/Enums/CardHeadType.swift
  DOTCHI/DOTCHI/Global/Enums/CardSortType.swift
  DOTCHI/DOTCHI/Global/Enums/LuckyType.swift
  DOTCHI/DOTCHI/Global/Extensions/Adjusted+.swift
  DOTCHI/DOTCHI/Global/Extensions/UICollectionView+.swift
  DOTCHI/DOTCHI/Global/Extensions/UIImageView+.swift
  DOTCHI/DOTCHI/Global/Extensions/UILabel+.swift
  DOTCHI/DOTCHI/Global/Extensions/UIStackView+.swift
  DOTCHI/DOTCHI/Global/Protocols/ClassNameProtocol.swift
  DOTCHI/DOTCHI/Global/Protocols/a.swift
  DOTCHI/DOTCHI/Info.plist
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgDefaultDummy.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgDefaultDummy.imageset/imgDefaultDummy.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgHealthFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgHealthFront.imageset/imgHealthFront.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgLoveFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgLoveFront.imageset/imgLoveFront.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgLuckyFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgLuckyFront.imageset/imgLuckyFront.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgMoneyFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/imgMoneyFront.imageset/imgMoneyFront.svg
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiWhite.colorset/Contents.json
  DOTCHI/DOTCHI/Screens/Browse/BrowseViewController.swift
  DOTCHI/DOTCHI/Screens/Components/Buttons/DotchiCircleUIButton.swift
  DOTCHI/DOTCHI/Screens/Components/Buttons/DotchiSortUIButton.swift
  DOTCHI/DOTCHI/Screens/Components/CollectionViewCells/BrowseUICollectionViewCell.swift
  DOTCHI/DOTCHI/Screens/Components/Views/CardFrontUIView.swift
  DOTCHI/DOTCHI/Screens/Components/Views/CardProfileUIView.swift
  DOTCHI/DOTCHI/Screens/Components/Views/DotchiNavigationUIView.swift
  DOTCHI/DOTCHI/Supports/Environment.swift
Labels: chore 🧹, add ✚

#37 [CHORE] 행운별 모아보기 / Colorsets 네이밍 변경된 부분 적용
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Sources/Screens/Home/CollectionView.swift
Labels: chore 🧹

#38 [FEAT] 둘러보기 - 카드 뒷면 UI, 뒤집기 기능 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DOTCHI/DOTCHI/Global/Enums/LuckyType.swift
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgHealthBack.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgHealthBack.imageset/imgHealthBack.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgHealthFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgHealthFront.imageset/imgHealthFront.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLoveBack.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLoveBack.imageset/imgLoveBack.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLoveFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLoveFront.imageset/imgLoveFront.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLuckyBack.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLuckyBack.imageset/imgLuckyBack.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLuckyFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgLuckyFront.imageset/imgLuckyFront.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgMoneyBack.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgMoneyBack.imageset/imgMoneyBack.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgMoneyFront.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgMoneyFront.imageset/imgMoneyFront.svg
  DOTCHI/DOTCHI/Sources/Components/CollectionViewCells/BrowseUICollectionViewCell.swift
  DOTCHI/DOTCHI/Sources/Components/Views/CardBackUIView.swift
Labels: feat 💚

#39 [FEAT] 따봉도치 만들기 - 사진 UI 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Enums/LuckyType.swift
  DOTCHI/DOTCHI/Global/UIViewControllerRepresentable/MakeDotchiPhotoViewControllerRepresentable.swift
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnClose.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icnClose.imageset/icnClose.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icn_loadPhoto.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/icn/icn_loadPhoto.imageset/icn_loadPhoto.svg
  DOTCHI/DOTCHI/Sources/Components/Buttons/DotchiDoneUIButton.swift
  DOTCHI/DOTCHI/Sources/Components/CollectionViewCells/MakeDotchiUICollectionViewCell.swift
  DOTCHI/DOTCHI/Sources/Components/Views/DotchiNavigationUIView.swift
  DOTCHI/DOTCHI/Sources/Components/Views/MakeDotchiLuckyTitleUIView.swift
  DOTCHI/DOTCHI/Sources/Screens/ContentView.swift
  DOTCHI/DOTCHI/Sources/Screens/Make/MakeDotchiPhotoViewController.swift
Labels: chore 🧹, feat 💚

#42 [FEAT] 따봉도치 만들기 - 내용 작성 UI 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Bases/BaseUINavigationController.swift
  DOTCHI/DOTCHI/Global/Bases/BaseViewController.swift
  DOTCHI/DOTCHI/Global/Extensions/UITextField+.swift
  DOTCHI/DOTCHI/Global/UIViewControllerRepresentable/MakeDotchiPhotoViewControllerRepresentable.swift
  DOTCHI/DOTCHI/Sources/Components/TextFields/DotchiUITextField.swift
  DOTCHI/DOTCHI/Sources/Components/Views/DotchiNavigationUIView.swift
  DOTCHI/DOTCHI/Sources/Entities/MakeDotchiEntity.swift
  DOTCHI/DOTCHI/Sources/Screens/Make/MakeDotchiContentViewController.swift
  DOTCHI/DOTCHI/Sources/Screens/Make/MakeDotchiPhotoViewController.swift
Labels: feat 💚

#44 [FEAT] 따봉도치 만들기 - 내용 작성 기능 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Extensions/String+.swift
  DOTCHI/DOTCHI/Sources/Components/TextFields/DotchiUITextField.swift
  DOTCHI/DOTCHI/Sources/Screens/Make/MakeDotchiContentViewController.swift
Labels: chore 🧹, feat 💚

#49 [FEAT] 로그인 UI 구현 및 로그인 api 연결
  .gitignore
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI.xcodeproj/xcshareddata/xcschemes/DOTCHI-Debug.xcscheme
  DOTCHI/DOTCHI/DOTCHIApp.swift
  DOTCHI/DOTCHI/Global/Bases/BaseViewController.swift
  DOTCHI/DOTCHI/Global/Enums/KeychainKeys.swift
  DOTCHI/DOTCHI/Global/Enums/Message.swift
  DOTCHI/DOTCHI/Global/UIViewControllerRepresentable/SignInViewControllerRepresentable.swift
  DOTCHI/DOTCHI/Networks/DTO/Auth/Request/SignInRequestDTO.swift
  DOTCHI/DOTCHI/Networks/DTO/Auth/Response/SignInResponseDTO.swift
  DOTCHI/DOTCHI/Networks/Essentials/BaseResponseType.swift
  DOTCHI/DOTCHI/Networks/Routers/AuthRouter.swift
  DOTCHI/DOTCHI/Networks/Services/AuthService.swift
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgDotchiLogo.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgDotchiLogo.imageset/imgDotchiLogo.svg
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgSignInApple.imageset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/img/imgSignInApple.imageset/imgSignInApple.svg
  DOTCHI/DOTCHI/Sources/Screens/SignIn/SignInViewController.swift
  DOTCHI/DOTCHI/Supports/Debug.xcconfig
Labels: feat 💚

#60 [CHORE] 홈 - 따봉도치 둘러보기 뷰 연결
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Bases/BaseUINavigationController.swift
  DOTCHI/DOTCHI/Global/Extensions/UINavigationController+.swift
  DOTCHI/DOTCHI/Global/UIViewControllerRepresentable/BrowseViewControllerRepresentable.swift
  DOTCHI/DOTCHI/Sources/Screens/Browse/BrowseViewController.swift
  DOTCHI/DOTCHI/Sources/Screens/Home/HomeView.swift
Labels: chore 🧹

#62 [FEAT] 홈 API 연동
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Networks/DTO/Home/Response/HomeResponseDTO.swift
  DOTCHI/DOTCHI/Networks/Routers/HomeRouter.swift
  DOTCHI/DOTCHI/Networks/Services/HomeService.swift
  DOTCHI/DOTCHI/Sources/Screens/Home/AsyncImageView.swift
  DOTCHI/DOTCHI/Sources/Screens/Home/HomeView.swift
Labels: feat 💚

#63 [FEAT] 따봉도치 디테일(댓글) 뷰 API 연결
  DOTCHI/DOTCHI/Global/Extensions/UIImageView+.swift
  DOTCHI/DOTCHI/Global/UIViewControllerRepresentable/DotchiDetailViewControllerRepresentable.swift
  DOTCHI/DOTCHI/Networks/DTO/Card/Response/GetCommentsResponseDTO.swift
  DOTCHI/DOTCHI/Networks/Routers/CardRouter.swift
  DOTCHI/DOTCHI/Networks/Services/CardService.swift
  DOTCHI/DOTCHI/Sources/Components/CollectionViewCells/BrowseUICollectionViewCell.swift
  DOTCHI/DOTCHI/Sources/Entities/CardUserEntity.swift
  DOTCHI/DOTCHI/Sources/Screens/Browse/BrowseViewController.swift
  DOTCHI/DOTCHI/Sources/Screens/Detail/DotchiDetailViewController.swift
Labels: feat 💚

#66 [FEAT] 따봉도치 둘러보기 API 연결
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Global/Extensions/Encodable+.swift
  DOTCHI/DOTCHI/Networks/DTO/Card/Request/GetAllCardsRequestDTO.swift
  DOTCHI/DOTCHI/Networks/DTO/Card/Response/GetAllCardsResponseDTO.swift
  DOTCHI/DOTCHI/Networks/Essentials/APIConstants.swift
  DOTCHI/DOTCHI/Networks/Routers/CardRouter.swift
  DOTCHI/DOTCHI/Networks/Services/CardService.swift
  DOTCHI/DOTCHI/Sources/Entities/CardEntity.swift
  DOTCHI/DOTCHI/Sources/Screens/Browse/BrowseViewController.swift
Labels: feat 💚

#69 [FEAT] 인스타 스토리 공유하기 구현
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DOTCHI/DOTCHI/Global/Extensions/UIColor+.swift
  DOTCHI/DOTCHI/Global/Extensions/UIView+.swift
  DOTCHI/DOTCHI/Info.plist
  DOTCHI/DOTCHI/Networks/Essentials/APIConstants.swift
  DOTCHI/DOTCHI/Sources/Components/Views/InstagramShareUIView.swift
  DOTCHI/DOTCHI/Sources/Screens/Browse/BrowseViewController.swift
  DOTCHI/DOTCHI/Supports/ServiceEnvironment.swift
Labels: feat 💚

#71 [CHORE] APP ICON 적용
  DOTCHI/DOTCHI/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  DOTCHI/DOTCHI/Resources/Assets.xcassets/AppIcon.appiconset/icon.png
Labels: chore 🧹

#73 [FEAT] 마이페이지 조회 API 연동
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Networks/DTO/Home/Response/HomeResponseDTO.swift
  DOTCHI/DOTCHI/Networks/DTO/My/Response/MyResponseDTO.swift
  DOTCHI/DOTCHI/Networks/Routers/MyRouter.swift
  DOTCHI/DOTCHI/Networks/Services/HomeService.swift
  DOTCHI/DOTCHI/Networks/Services/MyService.swift
  DOTCHI/DOTCHI/Resources/Colorsets.xcassets/dotchiGray2.colorset/Contents.json
  DOTCHI/DOTCHI/Sources/Screens/My/MyView.swift
Labels: feat 💚

#75 [CHORE] card dotchiImageView layout 수정
  DOTCHI/DOTCHI/Sources/Components/CollectionViewCells/MakeDotchiUICollectionViewCell.swift
  DOTCHI/DOTCHI/Sources/Components/Views/CardFrontUIView.swift
Labels: chore 🧹

#77 [FIX] 따봉도치 디테일 - 댓글의 luckyType 적용 안 되는 문제 수정
  DOTCHI/DOTCHI/Sources/Screens/Detail/DotchiDetailViewController.swift
Labels: fix 🔨

#79 [CHORE] 따봉도치 디테일 뷰 present modal로 열리도록 변경
  DOTCHI/DOTCHI/Global/Bases/BaseViewController.swift
  DOTCHI/DOTCHI/Sources/Components/Views/DotchiNavigationUIView.swift
  DOTCHI/DOTCHI/Sources/Screens/Browse/BrowseViewController.swift
  DOTCHI/DOTCHI/Sources/Screens/Detail/DotchiDetailViewController.swift
  DOTCHI/DOTCHI/Sources/Screens/Make/MakeDotchiPhotoViewController.swift
Labels: chore 🧹

#82 [FEAT] 마이페이지 수정하기 API 연동
  DOTCHI/DOTCHI.xcodeproj/project.pbxproj
  DOTCHI/DOTCHI/Networks/DTO/My/Request/PatchMembersRequestDTO.swift
  DOTCHI/DOTCHI/Networks/DTO/My/Response/EditResonseDTO.swift
  DOTCHI/DOTCHI/Networks/Routers/MyRouter.swift
  DOTCHI/DOTCHI/Networks/Services/MyService.swift
  DOTCHI/DOTCHI/Sources/Screens/Home/AsyncImageView.swift
  DOTCHI/DOTCHI/Sources/Screens/My/MyView.swift
  DOTCHI/DOTCHI/Sources/Screens/My/ProfileEditView.swift
Labels: feat 💚
